name: solsol
channels:
  - conda-forge
dependencies:
  - python=3.10.2
  - pip=22.0.3
  - ta-lib=0.4.19
  - numpy=1.22.2
  - pandas=1.4.1
  - scipy=1.8.0
  - pip:
      - pyside6==6.3.0
      - pyqtgraph==0.12.4
      - requests==2.27.1
      - apscheduler==3.9.1
      - timesetter==1.2
      - websocket-client==1.3.1
      - pygments==2.11.2
      - dill==0.3.4
      - getmac==0.8.3
      - yapf==0.32.0
      # only for developers
      - black
      - pyarmor
      - pyinstaller
      - flake8
      - pep8-naming
      - flake8-variables-names
      - flake8-print
      - flake8-blind-except
      - flake8-comprehensions
      - flake8-use-fstring
      - pygount
