name: solie
channels:
  - conda-forge
dependencies:
  - python=3.10.8
  - pip=23.1.2
  - ta-lib=0.4.19
  - pip:
      - numpy==1.22.2
      - pandas==1.4.4
      - scipy==1.8.0
      - pyside6==6.5.1.1
      - qasync==0.26.0
      - pyqtgraph==0.13.3
      - aiohttp==3.8.6
      - cchardet==2.1.7
      - aiodns==3.1.1
      - aiofiles==23.2.1
      - apscheduler==3.9.1
      - timesetter==1.8
      - pygments==2.11.2
      - dill==0.3.4
      - yapf==0.32.0
      - getmac==0.8.3
      # developer dependencies
      - ruff
      - pyright
      - pygount
