name: solie
channels:
  - conda-forge
dependencies:
  - python=3.11.6
  - pip=23.3.1
  - pip:
      - numpy==1.26.2
      - pandas==1.5.3
      - scipy==1.11.3
      - pyside6==6.6.0
      - qasync==0.26.0
      - pyqtgraph==0.13.3
      - aiohttp==3.8.6
      - faust-cchardet==2.1.19
      - aiodns==3.1.1
      - aiofiles==23.2.1
      - apscheduler==3.10.4
      - timesetter==1.8
      - pygments==2.11.2
      - yapf==0.32.0
      - getmac==0.8.3
      - pandas-ta==0.3.14b
      # developer dependencies
      - ruff
      - pyright
      - pygount
