name: solie
channels:
  - conda-forge
dependencies:
  - python=3.10.8
  - pip=23.1.2
  - ta-lib=0.4.19
  - pip:
      - numpy==1.22.2
      - pandas==1.4.4
      - scipy==1.8.0
      - pyside6==6.3.1
      - pyqtgraph==0.12.4
      - requests==2.28.2
      - apscheduler==3.9.1
      - timesetter==1.8
      - websocket-client==1.3.1
      - pygments==2.11.2
      - dill==0.3.4
      - yapf==0.32.0
      - tendo==0.2.15
      - cryptography==37.0.4
      - getmac==0.8.3
      # developer dependencies
      - black
      - pyarmor
      - pyinstaller
      - flake8
      - pep8-naming
      - flake8-variables-names
      - flake8-print
      - flake8-comprehensions
      - flake8-use-fstring
      - pygount
      - pip-licenses
      - pipdeptree
      - pyyaml
