[tool.poetry]
name = "workspace"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.group.main.dependencies]
python = "^3.9,<3.13"

[tool.poetry.group.dev.dependencies]
solie = { path = "solie/", develop = true }
documentation = { path = "documentation/", develop = true }

[tool.poetry.dev-dependencies]
ruff = "*"
pyright = "*"
pygount = "*"

[tool.ruff]
extend-select = ["N", "I", "T20"]
exclude = ["solie/solie/user_interface.py"]

[tool.pyright]
typeCheckingMode = "basic"
ignore = ["solie/solie/user_interface.py"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
