name: solsol
dependencies:
  - python=3.10.2
  - pip=22.0.3
  - ta-lib=0.4.19
  - numpy=1.22.2
  - pandas=1.4.1
  - scipy=1.8.0
  - pip:
      - pyqt6==6.2.3
      - pyqtgraph==0.12.4
      - requests==2.27.1
      - apscheduler==3.9.1
      - timesetter==1.2
      - websocket-client==1.3.1
      - pygments==2.11.2
      - dill==0.3.4
      - pyzipper==0.3.5
      - getmac==0.8.3
      - black==22.1.0
